// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class 1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver(@D:\Programs\Mozila\firefox.exe), new FirefoxProfile(), TimeSpan.FromMinutes(10));
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void 1() {
    driver.Navigate().GoToUrl("https://www.google.com");
    driver.Manage().Window.Size = new System.Drawing.Size(1037, 597);
    driver.FindElement(By.Name("q")).SendKeys("123");
    driver.FindElement(By.Name("q")).SendKeys(Keys.Enter);
    driver.Close();
  }
}
